python3: do not open outfile in binary mode
If outfile is opened in binary mode a write can not write "str" but is
expected to write "bytes", but we are are writing "str" to it.

Tested with python2 and python3.

python3 output before the patch:
[21:01:35.184141 0.000001] Traceback (most recent call last):
  File "./grabserial", line 530, in <module>
    grab(sys.argv[1:])
  File "./grabserial", line 470, in grab
    out.write(msg)
TypeError: a bytes-like object is required, not 'str'

Signed-off-by: Henning Schild <henning@hennsch.de>